/*
 * DCSA OpenAPI specification for Track & Trace
 * API specification issued by DCSA.org
 *
 * OpenAPI spec version: 2.0.1
 * Contact: info@dcsa.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.dcsa.smartcontract.tnt.api;

import com.dcsa.smartcontract.tnt.ApiException;

import java.util.UUID;

import com.dcsa.tnt.common.EventTypeList;
import com.dcsa.tnt.common.Events;
import com.dcsa.tnt.common.InlineResponse200;
import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for EventsApi
 */
@Ignore
public class EventsApiTest {

    private final EventsApi api = new EventsApi();

    /**
     * Find events by eventID.
     *
     * Returns event with the specified eventID.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void eventsEventIDGetTest() throws ApiException {
        String eventID = null;
        InlineResponse200 response = api.eventsEventIDGet(eventID);

        // TODO: test validations
    }
    /**
     * Find events.
     *
     * Returns all events filtered by the parameters.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void eventsGetTest() throws ApiException {
        EventTypeList eventType = null;
        String bookingReference = null;
        String transportDocumentID = null;
        String equipmentReference = null;
        UUID scheduleID = null;
        UUID transportCallID = null;
        Events response = api.eventsGet(eventType, bookingReference, transportDocumentID, equipmentReference, scheduleID, transportCallID, null, null);

        // TODO: test validations
    }
}
