/*
 * DCSA OpenAPI specification for Track & Trace
 * API specification issued by DCSA.org
 *
 * OpenAPI spec version: 2.0.1
 * Contact: info@dcsa.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.dcsa.tnt.common;

import java.util.Objects;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.UUID;

/**
 * The equipment event entity is a specialization of the event entity to support specification of data that only applies to an equipment event.
 */
@Schema(description = "The equipment event entity is a specialization of the event entity to support specification of data that only applies to an equipment event.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-05-22T05:06:30.605Z[GMT]")
public class EquipmentEvent extends Event implements AnyOfeventsItems, OneOfinlineResponse200 {
  /**
   * Gets or Sets equipmentEventEventType
   */
  @JsonAdapter(EventTypeEnum.Adapter.class)
  public enum EventTypeEnum {
    EQUIPMENT("EQUIPMENT");

    private String value;

    EventTypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static EventTypeEnum fromValue(String text) {
      for (EventTypeEnum b : EventTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<EventTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final EventTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public EventTypeEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return EventTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }  @SerializedName("eventType")
  private EventTypeEnum equipmentEventEventType = null;

  /**
   * Unique identifier for Event Type Code. For equipment events this can be: - LOAD (Load) - DISC (Discharge) - GTIN (Gate in) - GTOT (Gate out) - STUF (Stuffing) - STRP (Stripping) 
   */
  @JsonAdapter(EventTypeCodeEnum.Adapter.class)
  public static enum EventTypeCodeEnum {
    LOAD("LOAD"),
    DISC("DISC"),
    GTIN("GTIN"),
    GTOT("GTOT"),
    STUF("STUF"),
    STRP("STRP");

    private String value;

    EventTypeCodeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static EventTypeCodeEnum fromValue(String text) {
      for (EventTypeCodeEnum b : EventTypeCodeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<EventTypeCodeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final EventTypeCodeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public EventTypeCodeEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return EventTypeCodeEnum.fromValue(String.valueOf(value));
      }
    }
  }  @SerializedName("eventTypeCode")
  private EventTypeCodeEnum eventTypeCode = null;

  @SerializedName("equipmentReference")
  private String equipmentReference = null;

  @SerializedName("emptyIndicatorCode")
  private EmptyIndicatorCode emptyIndicatorCode = null;

  @SerializedName("transportCallID")
  private UUID transportCallID = null;

  public EquipmentEvent equipmentEventEventType(EventTypeEnum equipmentEventEventType) {
    this.equipmentEventEventType = equipmentEventEventType;
    return this;
  }

   /**
   * Get equipmentEventEventType
   * @return equipmentEventEventType
  **/
  @Schema(example = "EQUIPMENT", description = "")
  public EventTypeEnum getEquipmentEventEventType() {
    return equipmentEventEventType;
  }

  public void getEquipmentEventEventType(EventTypeEnum equipmentEventEventType) {
    this.equipmentEventEventType = equipmentEventEventType;
  }

  public EquipmentEvent eventTypeCode(EventTypeCodeEnum eventTypeCode) {
    this.eventTypeCode = eventTypeCode;
    return this;
  }

   /**
   * Unique identifier for Event Type Code. For equipment events this can be: - LOAD (Load) - DISC (Discharge) - GTIN (Gate in) - GTOT (Gate out) - STUF (Stuffing) - STRP (Stripping) 
   * @return eventTypeCode
  **/
  @Schema(example = "LOAD", description = "Unique identifier for Event Type Code. For equipment events this can be: - LOAD (Load) - DISC (Discharge) - GTIN (Gate in) - GTOT (Gate out) - STUF (Stuffing) - STRP (Stripping) ")
  public String getEventTypeCode() {
    return eventTypeCode.getValue();
  }

  public void setEventTypeCode(EventTypeCodeEnum eventTypeCode) {
    this.eventTypeCode = eventTypeCode;
  }

  public EquipmentEvent equipmentReference(String equipmentReference) {
    this.equipmentReference = equipmentReference;
    return this;
  }

   /**
   * Get equipmentReference
   * @return equipmentReference
  **/
  @Schema(description = "")
  public String getEquipmentReference() {
    return equipmentReference;
  }

  public void setEquipmentReference(String equipmentReference) {
    this.equipmentReference = equipmentReference;
  }

  public EquipmentEvent emptyIndicatorCode(EmptyIndicatorCode emptyIndicatorCode) {
    this.emptyIndicatorCode = emptyIndicatorCode;
    return this;
  }

   /**
   * Get emptyIndicatorCode
   * @return emptyIndicatorCode
  **/
  @Schema(required = true, description = "")
  public EmptyIndicatorCode getEmptyIndicatorCode() {
    return emptyIndicatorCode;
  }

  public void setEmptyIndicatorCode(EmptyIndicatorCode emptyIndicatorCode) {
    this.emptyIndicatorCode = emptyIndicatorCode;
  }

  public EquipmentEvent transportCallID(UUID transportCallID) {
    this.transportCallID = transportCallID;
    return this;
  }

   /**
   * Get transportCallID
   * @return transportCallID
  **/
  @Schema(required = true, description = "")
  public UUID getTransportCallID() {
    return transportCallID;
  }

  public void setTransportCallID(UUID transportCallID) {
    this.transportCallID = transportCallID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EquipmentEvent equipmentEvent = (EquipmentEvent) o;
    return Objects.equals(this.equipmentEventEventType, equipmentEvent.equipmentEventEventType) &&
        Objects.equals(this.eventTypeCode, equipmentEvent.eventTypeCode) &&
        Objects.equals(this.equipmentReference, equipmentEvent.equipmentReference) &&
        Objects.equals(this.emptyIndicatorCode, equipmentEvent.emptyIndicatorCode) &&
        Objects.equals(this.transportCallID, equipmentEvent.transportCallID) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(equipmentEventEventType, eventTypeCode, equipmentReference, emptyIndicatorCode, transportCallID, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EquipmentEvent {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    equipmentEventEventType: ").append(toIndentedString(equipmentEventEventType)).append("\n");
    sb.append("    eventTypeCode: ").append(toIndentedString(eventTypeCode)).append("\n");
    sb.append("    equipmentReference: ").append(toIndentedString(equipmentReference)).append("\n");
    sb.append("    emptyIndicatorCode: ").append(toIndentedString(emptyIndicatorCode)).append("\n");
    sb.append("    transportCallID: ").append(toIndentedString(transportCallID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
