/*
 * DCSA OpenAPI specification for Track & Trace
 * API specification issued by DCSA.org
 *
 * OpenAPI spec version: 2.0.1
 * Contact: info@dcsa.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.dcsa.tnt.common;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * ErrorsInner
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-05-22T05:06:30.605Z[GMT]")
public class ErrorsInner {
  @SerializedName("reason")
  private String reason = null;

  @SerializedName("message")
  private String message = null;

  public ErrorsInner reason(String reason) {
    this.reason = reason;
    return this;
  }

   /**
   * High level error message.
   * @return reason
  **/
  @Schema(example = "invalidQuery", required = true, description = "High level error message.")
  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }

  public ErrorsInner message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Detailed error message.
   * @return message
  **/
  @Schema(example = "The request did not contain one of the three required query parameters.", required = true, description = "Detailed error message.")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErrorsInner errorsInner = (ErrorsInner) o;
    return Objects.equals(this.reason, errorsInner.reason) &&
        Objects.equals(this.message, errorsInner.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reason, message);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErrorsInner {\n");
    
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
