/*
 * DCSA OpenAPI specification for Track & Trace
 * API specification issued by DCSA.org
 *
 * OpenAPI spec version: 2.0.1
 * Contact: info@dcsa.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.dcsa.tnt.common;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.UUID;
/**
 * The object used by the POST event-subscriptions endpoint
 */
@Schema(description = "The object used by the POST event-subscriptions endpoint")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-05-22T05:06:30.605Z[GMT]")
public class EventSubscriptionBody {
  @SerializedName("callbackUrl")
  private String callbackUrl = null;

  @SerializedName("eventType")
  private EventTypeList eventType = null;

  @SerializedName("bookingReference")
  private String bookingReference = null;

  @SerializedName("transportDocumentID")
  private String transportDocumentID = null;

  @SerializedName("transportDocumentType")
  private TransportDocumentType transportDocumentType = null;

  @SerializedName("equipmentReference")
  private String equipmentReference = null;

  @SerializedName("scheduleID")
  private UUID scheduleID = null;

  @SerializedName("transportCallID")
  private UUID transportCallID = null;

  public EventSubscriptionBody callbackUrl(String callbackUrl) {
    this.callbackUrl = callbackUrl;
    return this;
  }

   /**
   * Get callbackUrl
   * @return callbackUrl
  **/
  @Schema(required = true, description = "")
  public String getCallbackUrl() {
    return callbackUrl;
  }

  public void setCallbackUrl(String callbackUrl) {
    this.callbackUrl = callbackUrl;
  }

  public EventSubscriptionBody eventType(EventTypeList eventType) {
    this.eventType = eventType;
    return this;
  }

   /**
   * Get eventType
   * @return eventType
  **/
  @Schema(description = "")
  public EventTypeList getEventType() {
    return eventType;
  }

  public void setEventType(EventTypeList eventType) {
    this.eventType = eventType;
  }

  public EventSubscriptionBody bookingReference(String bookingReference) {
    this.bookingReference = bookingReference;
    return this;
  }

   /**
   * Get bookingReference
   * @return bookingReference
  **/
  @Schema(description = "")
  public String getBookingReference() {
    return bookingReference;
  }

  public void setBookingReference(String bookingReference) {
    this.bookingReference = bookingReference;
  }

  public EventSubscriptionBody transportDocumentID(String transportDocumentID) {
    this.transportDocumentID = transportDocumentID;
    return this;
  }

   /**
   * Get transportDocumentID
   * @return transportDocumentID
  **/
  @Schema(description = "")
  public String getTransportDocumentID() {
    return transportDocumentID;
  }

  public void setTransportDocumentID(String transportDocumentID) {
    this.transportDocumentID = transportDocumentID;
  }

  public EventSubscriptionBody transportDocumentType(TransportDocumentType transportDocumentType) {
    this.transportDocumentType = transportDocumentType;
    return this;
  }

   /**
   * Get transportDocumentType
   * @return transportDocumentType
  **/
  @Schema(description = "")
  public TransportDocumentType getTransportDocumentType() {
    return transportDocumentType;
  }

  public void setTransportDocumentType(TransportDocumentType transportDocumentType) {
    this.transportDocumentType = transportDocumentType;
  }

  public EventSubscriptionBody equipmentReference(String equipmentReference) {
    this.equipmentReference = equipmentReference;
    return this;
  }

   /**
   * Get equipmentReference
   * @return equipmentReference
  **/
  @Schema(description = "")
  public String getEquipmentReference() {
    return equipmentReference;
  }

  public void setEquipmentReference(String equipmentReference) {
    this.equipmentReference = equipmentReference;
  }

  public EventSubscriptionBody scheduleID(UUID scheduleID) {
    this.scheduleID = scheduleID;
    return this;
  }

   /**
   * Get scheduleID
   * @return scheduleID
  **/
  @Schema(description = "")
  public UUID getScheduleID() {
    return scheduleID;
  }

  public void setScheduleID(UUID scheduleID) {
    this.scheduleID = scheduleID;
  }

  public EventSubscriptionBody transportCallID(UUID transportCallID) {
    this.transportCallID = transportCallID;
    return this;
  }

   /**
   * Get transportCallID
   * @return transportCallID
  **/
  @Schema(description = "")
  public UUID getTransportCallID() {
    return transportCallID;
  }

  public void setTransportCallID(UUID transportCallID) {
    this.transportCallID = transportCallID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventSubscriptionBody eventSubscriptionBody = (EventSubscriptionBody) o;
    return Objects.equals(this.callbackUrl, eventSubscriptionBody.callbackUrl) &&
        Objects.equals(this.eventType, eventSubscriptionBody.eventType) &&
        Objects.equals(this.bookingReference, eventSubscriptionBody.bookingReference) &&
        Objects.equals(this.transportDocumentID, eventSubscriptionBody.transportDocumentID) &&
        Objects.equals(this.transportDocumentType, eventSubscriptionBody.transportDocumentType) &&
        Objects.equals(this.equipmentReference, eventSubscriptionBody.equipmentReference) &&
        Objects.equals(this.scheduleID, eventSubscriptionBody.scheduleID) &&
        Objects.equals(this.transportCallID, eventSubscriptionBody.transportCallID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(callbackUrl, eventType, bookingReference, transportDocumentID, transportDocumentType, equipmentReference, scheduleID, transportCallID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventSubscriptionBody {\n");
    
    sb.append("    callbackUrl: ").append(toIndentedString(callbackUrl)).append("\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    bookingReference: ").append(toIndentedString(bookingReference)).append("\n");
    sb.append("    transportDocumentID: ").append(toIndentedString(transportDocumentID)).append("\n");
    sb.append("    transportDocumentType: ").append(toIndentedString(transportDocumentType)).append("\n");
    sb.append("    equipmentReference: ").append(toIndentedString(equipmentReference)).append("\n");
    sb.append("    scheduleID: ").append(toIndentedString(scheduleID)).append("\n");
    sb.append("    transportCallID: ").append(toIndentedString(transportCallID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
