/*
 * DCSA OpenAPI specification for Track & Trace
 * API specification issued by DCSA.org
 *
 * OpenAPI spec version: 2.0.1
 * Contact: info@dcsa.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.dcsa.tnt.common;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The code to identify the type of information that is related to the shipment. This code can have the values: - BOK (Booking) - SHI (Shipping Instruction) - VGM (Verified Gross Mass) - SRM (Shipment Release Message) - TRD (Transport Document) - ARN (Arrival Notice) 
 */
@JsonAdapter(ShipmentInformationTypeCode.Adapter.class)
public enum ShipmentInformationTypeCode {
  BOK("BOK"),
  SHI("SHI"),
  VGM("VGM"),
  SRM("SRM"),
  TRD("TRD"),
  ARN("ARN");

  private String value;

  ShipmentInformationTypeCode(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ShipmentInformationTypeCode fromValue(String text) {
    for (ShipmentInformationTypeCode b : ShipmentInformationTypeCode.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<ShipmentInformationTypeCode> {
    @Override
    public void write(final JsonWriter jsonWriter, final ShipmentInformationTypeCode enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ShipmentInformationTypeCode read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return ShipmentInformationTypeCode.fromValue(String.valueOf(value));
    }
  }
}
